version: "3.8"

services:
  pdf:
    build: .
    container_name: pdf-pdf
    ports:
      - "8085:8080"
      - "6001:6001"
    environment:
      - ENABLED_GET=true
      - ENABLED_POST=true
      - SECRET=sec
