name: Release to Docker

on:
  push:
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Calculate version
        id: spell
        uses: actoaps/version-spell@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          cache: gradle

      - name: Gradle Build
        run: |
          ./gradlew clean build -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_LOGIN -DversionOverride=$BUILD_ID
        env:
          SONAR_HOST: ${{ secrets.SONAR_HOST }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
          BUILD_ID: ${{ steps.spell.outputs.version }}

      - name: Set up QEMU for multiarch builds
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64/v8,amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build sso image and publish to Docker
        uses: docker/build-push-action@v3
        with:
          cache-to: type=gha,mode=max
          cache-from: type=gha
          context: .
          platforms: linux/amd64
          push: true
          tags: actoaps/chromium-pdf-gen:${{ steps.spell.outputs.version }},actoaps/chromium-pdf-gen:latest
